# This is a basic workflow to help you get started with Actions

name: send mail 1

# Controls when the workflow will run
on:
  schedule:
      # - cron: '*/5 * * * *'
      # 表达式生成  https://crontab.guru/
      # 此处是UTC时间 即北京时间 -8小时
      - cron: '40 2,12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "JOB1"
  JOB1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Send mail from gmail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.GMAIL_USERNAME}}
          password: ${{secrets.GMAIL_PASSWORD}}
          subject: Github Actions job result
          to: sungsun@163.com
          from: <sun gang> icedustdream@gmail.com
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          body: body example
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true

      - name: Send mail from 163
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{secrets.NETEASE_USERNAME}}
          password: ${{secrets.NETEASE_PASSWORD}}
          subject: Github Actions job result
          to: mjguy@163.com
          from: <sun gang> sungsun@163.com
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          body: body example
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
