# This is a basic workflow to help you get started with Actions

name: send mail

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sungang-flow"
  sungang-flow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.google.com
          account: ${{secrets.GMAIL_USERNAME}}
          password: ${{secrets.GMAIL_PASSWORD}}
          sender: sungang
          from: icedustdream@gmail.com
          to: sungsun@163.com
          subject: mail title.
          body: body example
          contentType: text/html
          # attachments: file://attachmets.json
